### ISSUE TITLE
Line-height propagation on more elements than 

### ISSUE THREAD

**Issue by yteitel** [readium/readium-js-viewer#218]
Hello,
I have an issue related to line height in some EPUB.
Here is the screenshot of the problem :
![line-height](https://cloud.githubusercontent.com/assets/4281447/4489144/9df4ed06-4a17-11e4-841d-79a89f588b77.png)
As you can see, from the third paragraph, everything has a small line-height.
The text highlighted is the picture shows that a part of the text specifies a line-height. This particular line-height has an impact in every paragraph (elements) that follows. If I remove the elements that contains line-height styles, the third paragraph renders properly but the next one will be crushed as the third paragraph also contains line-height styling.
The line-height comes from the book CSS :

``` css
.suptext {
    font-size:xx-small;
    **line-height:0.7em;**
    vertical-align:super;
    font-size:0.7em;
    position:relative;
}
```

If some more info are needed, I would be happy to provide it.
