### ISSUE TITLE
Red text in "Moby Dick" title wont change when selecting "Text and Background Color" settings. Only changes on text resizing.

### ISSUE THREAD

**Issue by duanwalker** [readium/readium-js-viewer#291]

**Comment by duanwalker** [comment]
https://mail.google.com/mail/u/0/?ui=2&ik=ce4ec53148&view=att&th=14bcce9526025e4e&attid=0.1&disp=safe&zw

![image](https://cloud.githubusercontent.com/assets/7536426/6450661/57e18b56-c0f7-11e4-9ef3-640d032c3807.png)

**Comment by danielweck** [comment]
Thanks Duan. Some EPUBs are authored with high-priority CSS rules relative to Readium's own styles
(within the style cascade). Even if we used the `!important` keyword to increase the chances of forcing a style override, there might still be cases when the Readium CSS would fail to take precedence. For a bullet-proof solution, I think that we need to approach this problem in the same way that we apply font size (deep in the DOM, e.g. in `style` attributes of textual fragments), at the cost of additional DOM manipulations though.

**Comment by duanwalker** [comment]
how could we share this with the student intern group?

**Comment by danielweck** [comment]
@duanwalker my comment above points out possible ways to fix Readium's support for style overrides. Are you referring to a group of student interns that could potentially help code this stuff? (sorry, I'm not sure I understand your question :) )

**Comment by rkwright** [comment]
Moby Dick (and all the sample code/books) is available here:
https://code.google.com/p/epub-samples/w/list

**Comment by duanwalker** [comment]
@danielweck  sorry should have been more specific. 
i was referring to the student interns helping out with the cloud reader testing. ric mentioned he would like to share this issue with them for their info.

**Comment by danielweck** [comment]
By the way, the "official" Moby Dick moved from Google Code to GitHub:
https://github.com/IDPF/epub3-samples/tree/master/30/moby-dick
Note that the text is *not* red in the original EPUB:

https://github.com/IDPF/epub3-samples/blob/master/30/moby-dick/OPS/css/stylesheet.css#L364

```css
@media all and (orientation:portrait) {
p { font-family: serif; }
}


@media all and (orientation:landscape) {
p { font-family: sans-serif; }

}
```

The Moby Dick EPUB that's in Readium's git repository contains **modified CSS styles**, which were used to test the impact of asynchronous media queries and CSS content generation, on the scroll-view layout algorithm (rendering "stabilization", stable full-frame dimensions). We intentionally authored red text into this ebook (using `!important` styling rules). See:

https://github.com/readium/readium-js-viewer/blob/develop/epub_content/moby_dick/OPS/css/stylesheet.css#L367

```css
@media all and (orientation:portrait) {
p {
    font-family: sans-serif;
    
    color: magenta !important;
}
}

@media all and (orientation:landscape) {
p { font-family: serif; color: red !important;}
}

body:last-child:after
{
    content: "END";
    color: blue;
    font-weight: bold;
}
```

As you can see on DivShot, the text is indeed red:
http://readium-cloudreader.divshot.io/?epub=epub_content%2Fmoby_dick
