### ISSUE TITLE
Chrome extension missing font glyphicons-halflings-regular.woff2

### ISSUE THREAD

**Issue by danielweck** [readium/readium-js-viewer#342]
```
GET
chrome-extension://xxx/fonts/glyphicons-halflings-regular.woff2
net::ERR_FILE_NOT_FOUND
```

This file is probably required by Bootstrap, via its CSS file:

https://github.com/twbs/bootstrap/tree/master/dist/fonts

```
glyphicons-halflings-regular.eot
glyphicons-halflings-regular.svg
glyphicons-halflings-regular.ttf	
glyphicons-halflings-regular.woff
glyphicons-halflings-regular.woff2
```

https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap.css#L263

```css
@font-face {
  font-family: 'Glyphicons Halflings';

  src: url('../fonts/glyphicons-halflings-regular.eot');
  src: url('../fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('../fonts/glyphicons-halflings-regular.woff2') format('woff2'), url('../fonts/glyphicons-halflings-regular.woff') format('woff'), url('../fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
}
```

As you can see, the WOFF2 font is missing in the Readium repository: https://github.com/readium/readium-js-viewer/tree/master/fonts
Note that the RequireJS  / plugins refactoring (ongoing work in feature branch) now fetches these types of lib dependencies via NPM, we do not "hardcode" this data in our source tree anymore.

Full stack trace:

curCSS @ readium-all.js:6600jQuery.extend.css @ readium-all.js:7192jQuery.each.jQuery.cssHooks.(anonymous function).get @ readium-all.js:7215jQuery.extend.css @ readium-all.js:7187(anonymous function) @ readium-all.js:10714jQuery.access @ readium-all.js:4618jQuery.each.jQuery.each.jQuery.fn.(anonymous function) @ readium-all.js:10689setAppSize @ readium-all.js:52400loadLibraryUI @ readium-all.js:52406(anonymous function) @ readium-all.js:52446(anonymous function) @ readium-all.js:14072target.(anonymous function) @ extensions::SafeBuiltins:19safeCallbackApply @ extensions::sendRequest:21handleResponse @ extensions::sendRequest:73
