### ISSUE TITLE
TOC link into document heading, pagination fails to scroll-to-view on second time (stuck on last page)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-js-viewer#404]
To reproduce:
Accessible EPUB 3 ebook from the built-in library:
https://github.com/readium/readium-js-viewer/tree/develop/epub_content/accessible_epub_3

http://development.readium.divshot.io/?epub=epub_content%2Faccessible_epub_3

Any sub-heading in "2. Building a Better EPUB: Fundamental Accessibility": first time should link fine into the paginated content. Try another heading within the same document (under the same top-level heading). At some point, you will see that the page is "stuck" at the last CSS column, like if the CFI navigation engine fails to determine the correct location.

This is not due to recent changes (I checked by using `git log` to revert back to prior commit SHAs). It most probably is a long-standing bug, that only occurs under certain conditions. It is easily reproducible with the aforementioned EPUB though.

I will test-drive @JCCR 's "intel" branch(es) to see if it makes any positive difference.

**Comment by danielweck** [comment]
Ah, culprit is 

https://github.com/readium/readium-shared-js/blob/develop/js/views/reflowable_view.js#L389
https://github.com/readium/readium-shared-js/blob/feature/intel-cfi-improvements/js/views/reflowable_view.js#L389
```javascript
else if(pageRequest.elementId) {
            pageIndex = _navigationLogic.getPageForElementId(pageRequest.elementId);
        }
```

`getPageForElementId` >> `getPageForPointOnElement`:

https://github.com/readium/readium-shared-js/blob/develop/js/views/cfi_navigation_logic.js#L604
```javascript
this.getPageForPointOnElement = function($element, x, y) { 

var pageIndex; 
if (options.rectangleBased) { 
pageIndex = findPageByRectangles($element, y); 
if (pageIndex === null) { 
console.warn('Impossible to locate a hidden element: ', $element); 
return 0; 
} 
return pageIndex; 
} 

https://github.com/readium/readium-shared-js/blob/feature/intel-cfi-improvements/js/views/cfi_navigation_logic.js#L1068
```javascript
this.getPageForPointOnElement = function ($element, x, y) { 
 
var pageIndex; 
if (options.rectangleBased) { 
pageIndex = findPageByRectangles($element, y); 
if (pageIndex === null) { 
console.warn('Impossible to locate a hidden element: ', $element); 
return 0; 
} 
return pageIndex; 
} 
 
var posInElement = this.getVerticalOffsetForPointOnElement($element, x, y); 
return Math.floor(posInElement / $viewport.height()); 
}; 
```

var posInElement = this.getVerticalOffsetForPointOnElement($element, x, y); 
return Math.floor(posInElement / $viewport.height()); 
}; 
```


`pageIndex` is 38 (out of 39 total pages / CSS columns `_paginationInfo.columnCount`) so it looks like `_navigationLogic.getPageForElementId` fails to return the correct value (in `develop` and `intel-cfi-inmprovements`). @JCCR what do you think? I am using Chrome's debugger to step through the code, but I will place `console.debug()` statements instead, as I want to make sure that the DOM rendering state is not disrupted by the debugger (CSS column-ization in progress, maybe `Helpers.triggerLayout()` problem?).

**Comment by danielweck** [comment]
In other words, the common denominator between `develop` and `feature/intel-cfi-improvements` is `findPageByRectangles()`:

https://github.com/readium/readium-shared-js/blob/develop/js/views/cfi_navigation_logic.js#L604

https://github.com/readium/readium-shared-js/blob/feature/intel-cfi-improvements/js/views/cfi_navigation_logic.js#L316

```javascript
    function findPageByRectangles($element, spatialVerticalOffset) {
        var visibleContentOffsets = getVisibleContentOffsets();
        var elementRectangles = getNormalizedRectangles($element, visibleContentOffsets);
        var clientRectangles  = elementRectangles.clientRectangles;
        if (clientRectangles.length === 0) { // elements with display:none, etc.
            return null;
        }

        return calculatePageIndexByRectangles(clientRectangles, spatialVerticalOffset);
    }
```

Note that this function works fine on first TOC click, but fails subsequently. So it must have something to do with the state of DOM rendering? (CSS Columns?)

**Comment by danielweck** [comment]
Ah, `pageIndex` is out of bounds (`48` greater than `39`), and gets normalised to the last page-- (`38`):

```javascript
if (pageIndex < 0) {
            pageIndex = 0;
        }
        else if (pageIndex >= (options.paginationInfo ? options.paginationInfo.columnCount : 1)) {
            pageIndex = (options.paginationInfo ? (options.paginationInfo.columnCount - 1) : 0);
        }
```

In fact, @JCCR to test this you can click on the TOC link "Semantic Inflection" several times in a row, and observe how the heading if first displayed correctly (position in CSS columns), then subsequent hyperlink clicks result in the CSS viewport shifting! (until the out of bounds page number is reached)

**Comment by danielweck** [comment]
By the way, I disabled the font-faces in `epub.css`, to make sure this isn't interfering:

```css

@font-face {
  font-family: "Free Serif";
  font-style: normal;
  font-weight: normal;
  src: url(../fonts/FreeSerif.otf);
}

@font-face {
  font-family: "Free Sans Bold";
  font-style: normal;
  font-weight: bold;
  src: url(../fonts/FreeSansBold.otf);
}

@font-face {
  font-family: "Ubuntu Mono";
  font-weight: normal;
  font-style: normal;
  src: url(../fonts/UbuntuMono-R.ttf);
}

@font-face {
  font-family: "Ubuntu Mono Bold";
  font-style: normal;
  font-weight: bold;
  src: url(../fonts/UbuntuMono-B.ttf);
}

@font-face {
  font-family: "Ubuntu Mono BoldItal";
  font-weight: bold;
  font-style: italic;
  src: url(../fonts/UbuntuMono-BI.ttf);
}

@font-face {
  font-family: "Ubuntu Mono Ital";
  font-weight: normal;
  font-style: italic;
  src: url(../fonts/UbuntuMono-RI.ttf);
}
```
